### ISSUE TITLE
another problem plot: when you plot each dependent datapoint

### ISSUE THREAD

**Issue by samjlord** [cxli233/FriendsDontLetFriends#3]
A common problem, in my field at least, is plotting multiple dependent measurement on each sample. For example, if a researcher applies a drug to a dish of cells, then measures 100 cells in that dish, they often then plot 100 datapoints. This is incorrect, because there was only one sample, and the repeated measurements on that sample should not count toward the sample size.

We wrote about it here: https://rupress.org/jcb/article/219/6/e202001064/151717/SuperPlots-Communicating-reproducibility-and

**Comment by cxli233** [comment]
I wrote about this in my other repository "Online_R_learning": https://github.com/cxli233/Online_R_learning/blob/master/R_codes/08_Repeated_measures.Rmd . I talked about how to handle repeated measures (dependent samples). I don't have a specific section for repeated measures in this repository though. I might add it later.
